resources:
  repositories:
  - repository: common-templates
    type: github
    name: wso2-enterprise/choreo-common-pipeline-templates
    endpoint: wso2-enterprise

trigger:
  batch: true
  branches:
    include:
    - wso2-main

pr: none

variables:
- name: CONTAINER_REGISTRY
  value: choreocontrolplane.azurecr.io
- name: REPOSITORY
  value: choreoipaas/wso2-opensearch-k8s-operator
- name: APP_REVISION
  value: $(Build.SourceBranchName)-$(Build.SourceVersion)

pool:
  vmImage: "ubuntu-latest"

steps:
- task: Docker@2
  displayName: "Docker Build"
  inputs:
    command: build
    Dockerfile: "opensearch-operator/Dockerfile"
    buildContext: "opensearch-operator"
    containerRegistry: "wso2choreo-control-plane-acr"
    repository: $(REPOSITORY)
    tags: |
      $(APP_REVISION)
      latest
- template: install/install-trivy.yaml@common-templates
- template: pr/trivy-scan.yaml@common-templates
  parameters:
    IMAGES:
    - $(CONTAINER_REGISTRY)/$(REPOSITORY):$(APP_REVISION)
- task: Docker@2
  displayName: "Push Docker image"
  inputs:
    command: push
    containerRegistry: 'wso2choreo-control-plane-acr'
    repository: $(REPOSITORY)
    tags: |
      latest
      $(APP_REVISION)
