resources:
  repositories:
  - repository: common-templates
    type: github
    name: wso2-enterprise/choreo-common-pipeline-templates
    endpoint: wso2-enterprise

trigger: none

pr:
  branches:
    include:
    - '*'

variables:
- name: CONTAINER_REGISTRY
  value: choreocontrolplane.azurecr.io
- name: REPOSITORY
  value: choreoipaas/wso2-opensearch-k8s-operator
- name: APP_REVISION
  value: $(Build.SourceBranchName)-$(Build.SourceVersion)

pool:
  vmImage: "ubuntu-latest"

steps:
- task: Docker@2
  displayName: "Docker Build"
  inputs:
    command: build
    Dockerfile: "opensearch-operator/Dockerfile"
    buildContext: "opensearch-operator"
    containerRegistry: "wso2choreo-control-plane-acr"
    repository: $(REPOSITORY)
    tags: |
      $(APP_REVISION)
      latest
- template: install/install-trivy.yaml@common-templates
- script: |
    set -eo pipefail
    trivy image --exit-code 1 \
    --severity HIGH,CRITICAL \
    --no-progress \
    --ignorefile .trivyignore \
    $(CONTAINER_REGISTRY)/$(REPOSITORY):$(APP_REVISION)
